### ISSUE TITLE
Snow glitch

### ISSUE THREAD

**Issue by ryanw-ny** [mc-server/Gallery#45]
You can place snow on other people's claims. Not the block, just regular snow. It sends the "You are not allowed to build here" message but still places the snow. You can not go over 1 block height while placing the snow. This glitch only works if there is already one blanket of snow on the ground.

**Comment by madmaxoft** [comment]
The snow is still glitching due to a bug in MCServer. The snow level is increased only client-side, after relogging, the snow is back to its original level.
